In [1]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(7)

Using TensorFlow backend.


In [2]:
X_train=numpy.load('/home/julian/Downloads/imdb.npz_FILES/x_train.npy')
y_train=numpy.load('/home/julian/Downloads/imdb.npz_FILES/y_train.npy')
X_test=numpy.load('/home/julian/Downloads/imdb.npz_FILES/x_test.npy')
y_test=numpy.load('/home/julian/Downloads/imdb.npz_FILES/y_test.npy')

In [3]:
top_words = 100000
X_train=X_train[0:2000]
y_train=y_train[0:2000]
X_test=X_test[0:2000]
y_test=y_test[0:2000]

In [4]:
print(y_train.shape)

(2000,)


In [8]:
# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2000, 500)
(2000, 500)
(2000,)
(2000,)


In [43]:
# create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test),epochs=2,batch_size=64)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_16 (Embedding)     (None, 500, 32)           3200000   
_________________________________________________________________
lstm_16 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 101       
Total params: 3,253,301
Trainable params: 3,253,301
Non-trainable params: 0
_________________________________________________________________
None
Train on 2000 samples, validate on 2000 samples
Epoch 1/2
2000/2000 [==============================] - 274s - loss: 0.2456 - acc: 0.9850 - val_loss: 6.7181e-05 - val_acc: 1.0000
Epoch 2/2
2000/2000 [==============================] - 342s - loss: 3.8504e-05 - acc: 1.0000 - val_loss: 2.6356e-05 - val_acc: 1.0000


In [44]:
score = model.evaluate(X_test,y_test,verbose=0)


In [47]:
score

[2.6356030502938665e-05, 1.0]

In [49]:
y_pred=model.predict(X_test,batch_size=64,verbose=0)

In [67]:
print('predicted', '     ' , 'actual')
for i in range(100):
    print(y_pred[i],y_test[i])

('predicted', '     ', 'actual')
(array([ 0.99997354], dtype=float32), 1)
(array([ 0.99997413], dtype=float32), 1)
(array([ 0.9999733], dtype=float32), 1)
(array([ 0.99997389], dtype=float32), 1)
(array([ 0.99997413], dtype=float32), 1)
(array([ 0.99997389], dtype=float32), 1)
(array([ 0.9999733], dtype=float32), 1)
(array([ 0.99997377], dtype=float32), 1)
(array([ 0.99997354], dtype=float32), 1)
(array([ 0.99997294], dtype=float32), 1)
(array([ 0.99997401], dtype=float32), 1)
(array([ 0.99997306], dtype=float32), 1)
(array([ 0.99997354], dtype=float32), 1)
(array([ 0.99997425], dtype=float32), 1)
(array([ 0.99997318], dtype=float32), 1)
(array([ 0.99997342], dtype=float32), 1)
(array([ 0.99997389], dtype=float32), 1)
(array([ 0.9999733], dtype=float32), 1)
(array([ 0.99997401], dtype=float32), 1)
(array([ 0.99997389], dtype=float32), 1)
(array([ 0.99997413], dtype=float32), 1)
(array([ 0.99997318], dtype=float32), 1)
(array([ 0.99997365], dtype=float32), 1)
(array([ 0.9999733], dtype=